PASSWORD_LENGTH = 8
ONBOARD_SUBJECT = "Welcome to RBIM! Let's get started your account."
PASSWORD_UPDATED_SUBJECT = "Welcome to RBIM! your account is reset."
USER_ROLES = ['superadmin', 'barangay', 'data_reviewer', 'data_collector']
AUTH_END_ERROR_MSG = "Unable to identify the user"
SADMIN_AUTH_END_ERROR_MSG = "You do not have permission to perform this action"
EMAIL_NOT_FOUND_ERROR_MSG = "Entered email not found"
USER_NOT_FOUND_ERROR_MSG = "User not found"
DATA_NOT_FOUND_ERROR_MSG = "Data not found"
SURVEY_STATUS = ['survey_assigned' , 'survey_review_started', 'survey_rejected' , 'survey_review_submitted', 'pending_for_approval' , 'survey_verification_started' , 'survey_completed', 'survey_recorrection']
SURVEY_TYPE = ['regular', 'ocr']
OCR_STATUS = ['0/4', '1/4', '2/4', '3/4', '4/4']
EMAIL_EXISTS_ERROR_MSG = "Email already exists."
EMAIL_MANDATORY_ERROR_MSG = "Please enter your e-mail to proceed."
INVALID_EMAIL_ERROR_MSG = "You have entered an invalid e-mail address."
PASSWORD_MANDATORY_ERROR_MSG = "Please enter your password to proceed."
FIRSTNAME_MANDATORY_ERROR_MSG = "Please enter your first name to proceed."
PHONENO_EXISTS_ERROR_MSG = "Phone number already exists."
CITY_MANDATORY_ERROR_MSG = "City is required."
MUNICIPALITY_MANDATORY_ERROR_MSG = "Municipality is required."
LOCATION_MANDATORY_ERROR_MSG = "Location is required."
PASSWORD_WRONG_ERROR_MSG = "You have entered wrong password ; reset "
NOT_ACCESS_ERROR_MSG = "You are not access for the panel. contact to admin"
INVALID_ACCOUNT_ACCESS_ERROR_MSG = "You are not access for datacollector account. contact to admin"
META_KEY_MANDATORY_ERROR_MSG = "Please enter meta_key."
META_VALUE_MANDATORY_ERROR_MSG = "Please enter meta_value."
SURVEY_NUMBER_MANDATORY_ERROR_MSG = "Please enter your survey number to proceed."
SURVEY_NUMBER_EXISTS_ERROR_MSG = "Survey number already exists."
SURVEY_UNPROCESSABLE_ERROR_MSG = "Unprocessable"
INVALID_SURVEY_ERROR_MSG = "Invaild Survey"
UNPROCESSABLE_SURVEY_ERROR_MSG = "Unprocessable context"
SURVEY_REVIEW_ERROR_MSG = "The survey has not reviewed by the data reviewer"
REGISTRATION_FAILED_ERROR_MSG = "Registration failed"
USER_UNAUTHORIZED_ERROR_MSG = "Unauthorized user"
TASK_NOT_FOUND_ERROR_MSG = "Tasks not found"
PASSWORD_LENGTH_INVALID_ERROR_MSG = "password should contain min of {} characters"
KEYS_REQUIRED_ERROR_MSG = "{} - is required"
VERIFICATION_CODE_INVALID_ERROR_MSG = "Please enter the right code or resend the code again"
MONTH_NUMBER_LIST = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
MONTH_NAME_LIST = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']
NOTIFICATION_CLEAR_MSG = "Notification successfully cleared"
NOTIFICATION_DELETE_MSG = "Notification deleted successfully"
OCR_FILE_EXTENSION = ["jpg", "jpeg", "png"]
SURVEY_REPORT_SELECT_ERROR_MSG = "Please select the survey you want to download"
